fixed_coordinates: {
   storage_table: {x: -2.4547, y: -1.916, z: 0.88447, w: 0.4666},

   stand_by: {x: -1.7747, y: -0.54035, z: -0.4523, w: 0.8924},

   table_left: {x: 0.095037, y: 0.12586, z: -0.5222, w: 0.85282},

   table_right: {x: -2.6712, y: -2.1944, z: -0.3984, w: 0.9172}
}


pre_grasp: {torso_lift_joint: 1, 
            arm_1_joint: 1,
            arm_2_joint: 1,
            arm_3_joint: 1,
            arm_4_joint: 1,
            arm_5_joint: 1,
            arm_6_joint: 1,
            arm_7_joint: 1}


wit_api_key: GG424C7762FEFSTDI2BWR3MZQMO6UPUP