fixed_coordinates: {
   storage_table: {x: 3.8, y: 3.4, z: 0.5, w: 0.42},

   stand_by: {x: 4.58, y: 4.4, z: 0.5, w: 0.42},

   table_left: {x: -1.43, y: 0.09, z: 0.5, w: 0.42},

   table_right: {x: 2.09, y: 1.82, z: 0.5, w: 0.42}
}